[package]
name = "evu"
version = "0.1.0"
authors = ["Norberto Lopes <nlopes.ml@gmail.com>"]
edition = "2018"

[[bin]]
name = "evu"
doc = false

[dependencies]
arq = { path = "../arq" }
clap = { version = "4.0", features = ["cargo"] }
rpassword = "7.0"
